### ISSUE TITLE
IllegalStateException Fragment has not been attached yet

### ISSUE THREAD

**Issue by IbrahimDisouki** [kejunxia/AndroidMvc#72]
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.example.example.ui.activities.MainActivity}: java.lang.IllegalStateException: Fragment has not been attached yet.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2689)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
Caused by java.lang.IllegalStateException: Fragment has not been attached yet.
       at android.support.v4.app.Fragment.instantiateChildFragmentManager(Unknown Source)
       at android.support.v4.app.Fragment.getChildFragmentManager(Unknown Source)
       at com.shipdream.lib.android.mvc.MvcActivity$DelegateFragment.traverseFragmentAndSubFragments(Unknown Source)
       at com.shipdream.lib.android.mvc.MvcActivity$DelegateFragment.traverseFragmentAndSubFragments(Unknown Source)
       at com.shipdream.lib.android.mvc.MvcActivity$DelegateFragment.notifyAllSubMvcFragmentsTheirStateIsManagedByMe(Unknown Source)
       at com.shipdream.lib.android.mvc.MvcActivity$DelegateFragment.onPreViewReady(Unknown Source)
       at com.shipdream.lib.android.mvc.MvcFragment.onViewCreated(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.modifiesAlpha(Unknown Source)
       at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(Unknown Source)
       at android.support.v4.app.FragmentController.dispatchActivityCreated(Unknown Source)
       at android.support.v4.app.FragmentActivity.onStart(Unknown Source)
       at android.support.v7.app.AppCompatActivity.onStart(Unknown Source)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
       at android.app.Activity.performStart(Activity.java:6328)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2754)
       at android.app.ActivityThread.access$900(ActivityThread.java:177)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5938)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)`

**Comment by kejunxia** [comment]
The issue could be caused by a come and go bug reported for a long time in here 
https://issuetracker.google.com/issues/37122334
and here
https://issuetracker.google.com/issues/37000979

In earlier version of AndroidMvc there was a hack to work around the Android support library issue above. And then the issue was fixed, but reintroduced again. Hope the issue will be fixed in future support library.

Solution
Try downgrade the Android support lib to 25.0.1 and earlier AndroidMvc lib
